### PR TITLE
Update matcher.py

### PR DESCRIPTION
**Pull request by SultanOrazbayev**
Correcting a small typo.

### CODE REVIEW

**Comment by titipata** [comment]
thanks for the fix @SultanOrazbayev !

**Comment by titipata** [comment]
I also just updated some documentation of the matcher [here](https://github.com/titipata/affiliation_parser/blob/master/affiliation_parser/matcher.py#L30-L41). Let me know if it works fine for you.

**Comment by SultanOrazbayev** [comment]
Yes, this looks good, also good that you changed the `exact` matching on institution!

**Comment by titipata** [comment]
@SultanOrazbayev, yes, just noticed that! fixed :)

**Pull request merged**
